version: '3.8'
services
  db:
    image: postgres: 13
    environment:
      POSTGRES_USER: nicolas
      POSTGRES_PASSWORD: Nicolas2003
      POSTGRES_DB: mydatabase
    volumes:
      - ./db/init.sql:/docker-entrypoint-init.d/init.sql
    ports:
      - "5432:5432"
    web:
      build: ./api
      command: python app.py
      volumes:
        - ./api:/app
      ports:
        - "5000:5000"
      depends_on:
         -db
